/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.GildedRose;

public class GildedRose {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new GildedRose().getGreeting());
    }
}
