/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.GildedRose;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        GildedRose classUnderTest = new GildedRose();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
