/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.GildedRose;

import org.junit.Test;
import static org.junit.Assert.*;

public class GildedRoseTest {
    // @Test
    // void foo() {
    //     Item[] items = new Item[] { new Item("foo", 0, 0) };
    //     GildedRose app = new GildedRose(items);
    //     app.updateQuality();
    //     assertEquals("fixme", app.items[0].name);
    // }
}
